title: Aegisub Esp
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://rcuchiha.github.io

aux_links:
  Template Repository: https://github.com/rcuchiha/aegi-esp
