title: Aegisub Esp
description: Documentación de Aegisub en español
theme: just-the-docs

url: https://rcuchiha.github.io/aegi-esp

aux_links:
  Template Repository: https://github.com/RcUchiha/aegi-esp
